# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38c92e667e261d735f385b76fdc262f5f59f2cc62f9ab3fa5197ade4eba4c176fea3c00bcb8d5c8b5dfc8b71b42112c975a492bd028a7af7f77129f28000cef

test:
  secret_key_base: 943effee549632ce12eee270411c1438f0042cf790726466b617622843121cf4bfef1c3ab003ed3f0cd4e422d1820ce8a1b4c19465c31ee5b3cdb0d10c862ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
